name: stack-setup-info-gen
version: 0.0.0

dependencies:
- base
- bytestring
- classy-prelude
- http-conduit
- text
- containers

library:
  source-dirs: src

executables:
  setup-info-gen:
    source-dirs: app
    main: Main.hs
    dependencies: stack-setup-info-gen
