name: stack-setup-info-gen
version: 0.0.0

default-extensions:
- OverloadedStrings
- NoImplicitPrelude
- GeneralizedNewtypeDeriving
- LambdaCase

dependencies:
- base
- bytestring
- classy-prelude
- containers
- directory
- http-client
- http-client-tls
- text

library:
  source-dirs: src

executables:
  setup-info-gen:
    source-dirs: app
    main: Main.hs
    dependencies: stack-setup-info-gen

tests:
  generates-same-files:
    source-dirs: test
    main: Main.hs
    dependencies:
    - hspec
    - silently
    - stack-setup-info-gen
